//=====================================================
// This file was auto-generated by xlate_vreg v1.0
//            -->  DO NOT EDIT!  <-- 
//=====================================================
#ifndef _FPGA_REG_H
#define _FPGA_REG_H


//
// Register:    RTL_MAJOR
// Description: "major" portion of RTL revision "major.minor.build.rc"
//
#define RTL_MAJOR                                                    0x0000000000000000ULL


//
// Register:    RTL_MINOR
// Description: "minor" portion of RTL revision "major.minor.build.rc"
//
#define RTL_MINOR                                                    0x0000000000000004ULL


//
// Register:    RTL_BUILD
// Description: "build" portion of RTL revision "major.minor.build.rc"
//
#define RTL_BUILD                                                    0x0000000000000008ULL


//
// Register:    RTL_RC
// Description: "release candidate" portion of RTL revision "major.minor.build.rc"
//
#define RTL_RC                                                       0x000000000000000cULL


//
// Register:    RTL_DATE
// Description: RTL build date
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     year                           16  15:00 RO   n/a         Year
//     month                          8   23:16 RO   n/a         Month (1 thru 12)
//     day                            8   31:24 RO   n/a         Day (1 thru 31)
//
#define RTL_DATE                                                     0x0000000000000010ULL
#define RTL_DATE_year                                                0x1000000000000010ULL
#define RTL_DATE_month                                               0x0810000000000010ULL
#define RTL_DATE_day                                                 0x0818000000000010ULL


//
// Register:    RTL_TYPE
// Description: Uniquely identifies this RTL design
//
#define RTL_TYPE                                                     0x0000000000000014ULL


//
// Register:    RTL_SUBTYPE
// Description: Identifies the hardware platform this build is intended for 
//
#define RTL_SUBTYPE                                                  0x0000000000000018ULL



#endif
